config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http://localhost:3000
  phases:
    - duration: 10
      arrivalRate: 5
      # rampTo: 5
      name: Fase 1 /3
    - duration: 3
      arrivalRate: 5
      rampTo: 10
      name: Fase 2 (pico) /3
    - duration: 5
      arrivalRate: 5
      rampTo: 1
      name: Fase 3/ 3
  # Load & configure a couple of useful plugins
  # https://artillery.io/docs/reference/extensions
  # plugins:
  #   ensure:
  #     thresholds:
  #       - http.response_time.p99: 100
  #       - http.response_time.p95: 75
  #   apdex:
  #     threshold: 100
  #   metrics-by-endpoint: {}
scenarios:
  - flow:
      # - loop:
      - get:
          url: '/usuario'
      - post:
          url: '/api/sessions/registro'
      - post:
          url: '/api/sessions/login'
        # count: 100